-- Esquema base del proyecto.
-- Corresponde a la revisión Alembic: baseline_001.
--
-- Se ejecuta para preparar una base nueva.
-- Los cambios posteriores se aplican mediante Alembic.

BEGIN;

CREATE TABLE IF NOT EXISTS estado_reservas (
    id_estado_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS insumos (
    id_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    costo_unitario NUMERIC NOT NULL,
    unidad_medida VARCHAR NOT NULL,
    stock INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_edificio (
    id_tipo_edificio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_unidad (
    id_tipo_unidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS tipos_evento (
    id_tipo_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS cargos_personal (
    id_cargo_personal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS estados_incidencia (
    id_estados_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS tipos_incidencia (
    id_tipo_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR,
    activo BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS edificios (
    id_edificio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    direccion VARCHAR,
    created_at TIMESTAMP NOT NULL,
    id_tipo_edificio INTEGER NOT NULL,
    FOREIGN KEY (id_tipo_edificio)
        REFERENCES tipo_edificio(id_tipo_edificio)
);

CREATE TABLE IF NOT EXISTS espacios_comunes (
    id_espacio_comun INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    descripcion VARCHAR,
    capacidad INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    id_edificio INTEGER NOT NULL,
    FOREIGN KEY (id_edificio)
        REFERENCES edificios(id_edificio)
);

CREATE TABLE IF NOT EXISTS politicas_reserva (
    id_politica_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dias_anticipacion_min INTEGER NOT NULL,
    dias_anticipacion_max INTEGER NOT NULL,
    duracion_max_horas INTEGER NOT NULL,
    hora_apertura TIME NOT NULL,
    hora_cierre TIME NOT NULL,
    costo NUMERIC DEFAULT 0 NOT NULL,
    aforo_maximo INTEGER NOT NULL,
    deposito_garantia NUMERIC DEFAULT 0 NOT NULL,
    penalizaciones NUMERIC NOT NULL,
    id_espacio_comun INTEGER NOT NULL,
    id_tipo_evento INTEGER NOT NULL,
    FOREIGN KEY (id_espacio_comun)
        REFERENCES espacios_comunes(id_espacio_comun),
    FOREIGN KEY (id_tipo_evento)
        REFERENCES tipos_evento(id_tipo_evento)
);

CREATE TABLE IF NOT EXISTS unidades (
    id_unidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR NOT NULL,
    piso VARCHAR,
    created_at TIMESTAMP NOT NULL,
    id_edificio INTEGER NOT NULL,
    id_tipo_unidad INTEGER NOT NULL,
    FOREIGN KEY (id_edificio)
        REFERENCES edificios(id_edificio),
    FOREIGN KEY (id_tipo_unidad)
        REFERENCES tipo_unidad(id_tipo_unidad)
);

CREATE TABLE IF NOT EXISTS prioridades (
    id_prioridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    nivel INTEGER NOT NULL,
    tiempo_resolucion_horas INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL UNIQUE,
    descripcion VARCHAR
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    apellido VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    telefono VARCHAR NOT NULL,
    password_hash VARCHAR NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_rol INTEGER NOT NULL,
    FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
);

CREATE TABLE IF NOT EXISTS incidencias (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR NOT NULL,
    descripcion VARCHAR,
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_limite TIMESTAMP,
    fecha_resolucion TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    id_unidad INTEGER,
    id_tipo_incidencia INTEGER NOT NULL,
    id_prioridad INTEGER NOT NULL,
    id_espacio_comun INTEGER,
    id_reportante INTEGER,

    FOREIGN KEY (id_unidad)
        REFERENCES unidades(id_unidad),
    FOREIGN KEY (id_tipo_incidencia)
        REFERENCES tipos_incidencia(id_tipo_incidencia),
    FOREIGN KEY (id_prioridad)
        REFERENCES prioridades(id_prioridad),
    FOREIGN KEY (id_espacio_comun)
        REFERENCES espacios_comunes(id_espacio_comun),
    FOREIGN KEY (id_reportante)
        REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS intervenciones (
    id_intervencion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP,
    resultado VARCHAR,
    created_at TIMESTAMP,
    id_incidencia INTEGER NOT NULL,
    id_personal INTEGER NOT NULL,
    FOREIGN KEY (id_incidencia)
        REFERENCES incidencias(id_incidencia),
    FOREIGN KEY (id_personal)
        REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS intervencion_insumos (
    id_intervencion_insumos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_utilizada NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL,
    id_intervencion INTEGER NOT NULL,
    id_insumo INTEGER NOT NULL,
    FOREIGN KEY (id_intervencion)
        REFERENCES intervenciones(id_intervencion),
    FOREIGN KEY (id_insumo)
        REFERENCES insumos(id_insumo)
);

CREATE TABLE IF NOT EXISTS usuario_cargos (
    id_usuario_cargo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_cargo_personal INTEGER NOT NULL,
    FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario),
    FOREIGN KEY (id_cargo_personal)
        REFERENCES cargos_personal(id_cargo_personal)
);

CREATE TABLE IF NOT EXISTS residentes (
    id_residente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    FOREIGN KEY (id_unidad)
        REFERENCES unidades(id_unidad),
    FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS asignaciones (
    id_asignacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_asignacion TIMESTAMP NOT NULL,
    activa BOOLEAN DEFAULT TRUE NOT NULL,
    id_personal_asignado INTEGER NOT NULL,
    FOREIGN KEY (id_personal_asignado)
        REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS adjuntos_incidencia (
    id_adjuntos_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_archivo VARCHAR NOT NULL,
    nombre_original VARCHAR,
    tipo VARCHAR,
    fecha TIMESTAMP NOT NULL,
    id_usuario INTEGER NOT NULL,
    incidencias_id_incidencia INTEGER NOT NULL,
    FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario),
    FOREIGN KEY (incidencias_id_incidencia)
        REFERENCES incidencias(id_incidencia)
);

CREATE TABLE IF NOT EXISTS historial_incidencia (
    id_historial_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    version INTEGER NOT NULL,
    id_estado INTEGER NOT NULL,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    FOREIGN KEY (id_estado)
        REFERENCES estados_incidencia(id_estados_incidencia),
    FOREIGN KEY (id_incidencia)
        REFERENCES incidencias(id_incidencia),
    FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS reservas (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    cantidad_personas INTEGER NOT NULL,
    costo_total NUMERIC NOT NULL,
    observaciones VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    id_espacio_comun INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    id_tipo_evento INTEGER NOT NULL,
    id_estado_reserva INTEGER NOT NULL,
    FOREIGN KEY (id_espacio_comun)
        REFERENCES espacios_comunes(id_espacio_comun),
    FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario),
    FOREIGN KEY (id_tipo_evento)
        REFERENCES tipos_evento(id_tipo_evento),
    FOREIGN KEY (id_estado_reserva)
        REFERENCES estado_reservas(id_estado_reserva)
);

-- Índices utilizados por el módulo de incidencias.

CREATE INDEX IF NOT EXISTS idx_incidencias_reportante
    ON incidencias(id_reportante);

CREATE INDEX IF NOT EXISTS idx_adjuntos_incidencia
    ON adjuntos_incidencia(incidencias_id_incidencia);

CREATE INDEX IF NOT EXISTS idx_historial_incidencia_version
    ON historial_incidencia(id_incidencia, version DESC);

COMMIT;